language: c
sudo: required
dist: trusty
group: edge
os: linux

services:
  - docker
cache:
  directories:
    - $HOME/.docker

env:
  global:
    - PATH=$PATH:$HOME/.bin
  matrix:
    - OCAML_VERSION=4.02.3
    - OCAML_VERSION=4.03.0
    - OCAML_VERSION=4.04.1
    - OCAML_VERSION=4.05.0
    - OCAML_VERSION=4.06.0
matrix:
  allow_failures:
    - env: OCAML_VERSION=4.05.0
    - env: OCAML_VERSION=4.06.0

before_script:
  - |
    sed -i "s/__OCAML_VERSION__/$OCAML_VERSION/" travis/Dockerfile
    if md5sum --check ~/.docker/docker.md5 && [[ -f ~/.docker/image.tar ]] ; then
        docker load < ~/.docker/image.tar || exit 1
    else
        docker build -t ocaml-jupyter travis/ || exit 1
        docker save ocaml-jupyter > ~/.docker/image.tar || exit 2
        md5sum travis/* > ~/.docker/docker.md5
    fi

script:
  - docker run --rm -v $PWD:$PWD -w $PWD ocaml-jupyter ./travis/travis.sh
