language: c
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/.bin
    - $HOME/.opam
    - $HOME/.local
    # - $HOME/Library/Caches/Homebrew

addons:
  apt:
    sources:
      - sourceline: ppa:bpaquet/zeromq4-trusty
    packages:
      - m4
      - git
      - libffi-dev
      - libgmp-dev
      - libzmq-dev=4.0.4-bpa~trusty2

env:
  global:
    - PATH=$PATH:$HOME/.bin:$HOME/.local/bin
    - PYTHONUSERBASE=$HOME/.local

matrix:
  include:
    - os: linux
      env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.02.3
    - os: linux
      env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.03.0
    - os: linux
      env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.04.2
    - os: linux
      env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.05.0
    - os: linux
      env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.06.0+trunk
    # - os: osx
    #   osx_image: xcode7.3
    #   env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.04.2
  allow_failures:
    - os: linux
      env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.05.0
    - os: linux
      env: OPAM_VERSION=1.2.2 OCAML_VERSION=4.06.0+trunk

before_script:
  # - |-
  #   if [[ "$(type -p brew)" != '' ]]; then
  #     brew install m4 libffi zeromq cairo
  #   fi
  - pip install --user ipython==5.4.1 jupyter
  - |-
    if [[ "$(type -p opam)" == '' ]]; then
      mkdir -p $HOME/.bin
      curl -L -o $HOME/.bin/opam "https://github.com/ocaml/opam/releases/download/$OPAM_VERSION/opam-$OPAM_VERSION-$(uname -m)-$(uname -s)"
      chmod 755 $HOME/.bin/opam
      opam init -a -y --comp $OCAML_VERSION
    fi
  - eval $(opam config env)
  - opam install -y ocamlfind ocp-indent cairo2 archimedes
  - ocamlfind remove jupyter

script:
  # lint and code-format checks:
  - ./git/pre-commit
  - opam lint jupyter.opam
  # Installer:
  - opam pin add -y jupyter .
  - jupyter kernelspec list | grep ocaml-jupyter # kernel is installed.
  - opam remove jupyter
  - (! (jupyter kernelspec list | grep ocaml-jupyter)) # kernel is uninstalled.
  - (! ocamlfind query jupyter) # package is uninstalled.
  # Tests:
  - opam install -y camlp4 'ounit>=2.0.0'
  - ./configure --enable-tests
  - make
  - make test
